import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/assets/globals.css";
import Navbar from "@/app/components/navbar";
import Header from "@/app/components/header";

const geistSans = localFont({
  src: "./assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <Navbar />
          <div>
            <Header />
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
